### ISSUE TITLE
Tests fail for ember-lts-2.4 and ember-lts-2.8 with contentisFulfilled and isFulfilled

### ISSUE THREAD

**Issue by scottwernervt** [scottwernervt/ember-cli-group-by#2]
All integration tests are failing for Ember 2.4 and 2.8 LTS:

```javascript
not ok 5 Chrome 58.0 - helper:group-by-path: It groups by given single path
    ---
        actual: >
            contentisFulfilled
        expected: >
            AabBcd
        stack: >
                at http://localhost:7357/assets/tests.js:249:14
                at tryCatch (http://localhost:7357/assets/vendor.js:70691:14)
                at invokeCallback (http://localhost:7357/assets/vendor.js:70706:15)
                at publish (http://localhost:7357/assets/vendor.js:70674:9)
                at http://localhost:7357/assets/vendor.js:48982:7
                at invoke (http://localhost:7357/assets/vendor.js:17247:16)
        message: >
            AabBcd is the right order
        Log: |
    ...

not ok 5 Chrome 58.0 - helper:group-by-path: It groups by given single path
    ---
        actual: >
            isFulfilled
        expected: >
            AabBcd
        stack: >
                at http://localhost:7357/assets/tests.js:243:14
                at tryCatch (http://localhost:7357/assets/vendor.js:68307:14)
                at invokeCallback (http://localhost:7357/assets/vendor.js:68322:15)
                at publish (http://localhost:7357/assets/vendor.js:68290:9)
                at http://localhost:7357/assets/vendor.js:57770:16
                at invoke (http://localhost:7357/assets/vendor.js:18343:16)
        message: >
            AabBcd is the right order
        Log: |
    ...

```

**Comment by scottwernervt** [comment]
Oldest version tested is `ember-lts-2.12`.
